version: "3"
services:
    stdfile:
        image: rafaele/standardnotes:latest
        container_name: standardnotes
        restart: always
        volumes:
            - .:/data/
        ports:
            - "8888:8888"
