name: test
on: [push]
env:
  GO111MODULE: on
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Get dependencies
      run:
        go mod download
        go mod verify
    - name: Build code
      run: go build -v ./...
    - name: Test code
      run:
        go test -v ./...
